blank_issues_enabled: true
contact_links:
  - name: CESM forums
    url: https://bb.cgd.ucar.edu/cesm/
    about: For support with model use, troubleshooting, etc., please use the CESM forums
  - name: CAM issue
    url: https://github.com/ESCOMP/CAM/issues/new/choose
    about: Issue with CAM (Community Atmosphere Model)
  - name: CTSM / CLM issue
    url: https://github.com/ESCOMP/CTSM/issues/new/choose
    about: Issue with CTSM / CLM (Community Terrestrial Systems Model / Community Land Model)
